# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cade < Formula
  desc "Local, provider-agnostic orchestrator for AI coding workflows"
  homepage "https://github.com/Medalijal/cade"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Medalijal/cade/releases/download/v0.1.1/cade_0.1.1_darwin_amd64.tar.gz"
      sha256 "6ef208467feb178822c6b794f8a827ce0a099b1eb9b932b7a9cee8d6665b1e73"

      define_method(:install) do
        bin.install "cade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Medalijal/cade/releases/download/v0.1.1/cade_0.1.1_darwin_arm64.tar.gz"
      sha256 "11791eeff068c1f2b6b174663b158790f729d7e77a18f0a8cc1a7f8875ea5f2b"

      define_method(:install) do
        bin.install "cade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Medalijal/cade/releases/download/v0.1.1/cade_0.1.1_linux_amd64.tar.gz"
      sha256 "7651e6c4db9bcce773e10bab13b3aa9fa581d55538152cd8a569cffd0c884c7f"
      define_method(:install) do
        bin.install "cade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Medalijal/cade/releases/download/v0.1.1/cade_0.1.1_linux_arm64.tar.gz"
      sha256 "f00904bf59d3c0c5fdd3e0d51f64489664108740f1a226601c0be4939dfbbf2f"
      define_method(:install) do
        bin.install "cade"
      end
    end
  end

  test do
    (testpath/"config.json").write <<~JSON
      {"version":1,"accounts":{"test":{"provider":"codex","config_home":"#{testpath}","max_concurrency":1}}}
    JSON
    system "#{bin}/cade", "config", "validate", "config.json"
  end
end
